# Generated by Django 4.2.15 on 2024-09-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensiones',
            fields=[
                ('lpn', models.AutoField(primary_key=True, serialize=False)),
                ('largo', models.FloatField()),
                ('alto', models.FloatField()),
                ('ancho', models.FloatField()),
            ],
        ),
    ]
