# Generated by Django 4.2.15 on 2024-09-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionador_app_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensiones',
            name='lpn',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
